Repository sessac-3rd-team-A/BE, pull requests merged in 2024-01, with the labels that each got.

#154 refactor: diary
  src/main/java/back/ahwhew/entity/DiaryEntity.java
  src/main/java/back/ahwhew/repository/DiaryRepository.java
  src/main/java/back/ahwhew/service/DiaryService.java
Labels: refactor

#156 refactor: result필요없는 코드 삭제 및 리팩토링
  src/main/java/back/ahwhew/controller/MypageController.java
  src/main/java/back/ahwhew/controller/ResultController.java
  src/main/java/back/ahwhew/entity/ResultEntity.java
  src/main/java/back/ahwhew/repository/ResultRepository.java
  src/main/java/back/ahwhew/service/resultService/KarloService.java
  src/main/java/back/ahwhew/service/resultService/ResultService.java
Labels: refactor

#168 feat: https webconfig 설정 및 cors 설정
  src/main/java/back/ahwhew/config/WebConfig.java
Labels: enhancement

#176 fix: 회원정보 수정 시, 토큰 전달값 추가(#175)
  src/main/java/back/ahwhew/controller/MypageController.java
Labels: fix
